### ISSUE TITLE
Challenge Phase evaluation metric problems

### ISSUE THREAD

**Issue by HYheyue** [DeepSportradar/instance-segmentation-challenge#7]
Hi, as the competition deadline approaches, I've noticed that there seem to be some issues with the Challenge Phase evaluation system. My first and second submission results are identical, but the first one resulted in Failed, causing a missed submit. 

The results for the third submission show improvements in all mAP metrics except for "small" with 0 which is a strange phenomenon. I hope you can check whether there are any bugs in the evaluation script.

Due to the limitations on the number of submissions, I sincerely hope that you can respond to me as soon as possible.

**Comment by mistasse** [comment]
Hi,

- AFAIK, failed submissions do not count in the limit, only valid ones do.
- OM computation has been modified around the September, 20, in order to become more efficient. This could explain that your second submission worked and not the first. No significant difference has been noticed on OM (difference on all tried submissions was below 1e-6), no code has been changed for mAP computation.
- There are not many small objects in this dataset, mAP (small) is just there because MMDet's COCO metrics computes it, but I believe it to be completely uninteresting. At least, our baseline gets 0 as well.

If it was the other way around, i.e., that your first submission had worked and not the second, it would likely be because we were resizing outputs that didn't have the right resolution, and are not anymore. Us doing the upsampling is kind of introducing a bias, and requiring heavy compute for the evaluation server ;-) .

I think this sums up all the differences that may have been observed, and hope that it will reassure you ! I strongly believe that the evaluation process is more robust than it was.

**Comment by mistasse** [comment]
I forgot to mention. I also increased the total number of submission to 10. So if your first submission was prior to September 20, and really counted, it wouldn't prevent you from performing another submission in the 5-per-month limit.

**Comment by HYheyue** [comment]
Thank's for your reply, the number of submissions is indeed reasonable, but I get a non-zero value for "small" both in the test and the challenge dataset except the latest one. (Compared with the test phase, the challenge data get a higher mAP with small). This is confusing to me, especially considering that the other mAP metrics are all positive. 

I'm also checking my results and haven't found any obvious abnormalities yet.
